### PR TITLE
Publish enrollment

### PR DESCRIPTION
**Pull request by bhjLarson**
New enrollmenterror web page describing the BSD enrollment error.

### CODE REVIEW

**Comment by dvhart** [comment]
Hi Brad,

My wife is out of town, but she's back this afternoon. Lots of kid drama
until then it seems.

I took a quick look, and this contains ~7 merges and is based on an unknown
history - meaning out of the 83 listed changes in the pull request, a large
number of them are duplicates from the current project. This means that the
pull request was not based on dvhart/dbsmaps/master branch. I will have to
go through and identify which are duplicate patches and remove them and
resolve any conflicts this causes. This has been fairly doable in the past,
but there is always a risk for a major conflict, or that I apply an
incorrect merge solution. It takes more time, so it's harder for me to get
to it, but I'll do my best to do so by EOD tomorrow.

It would help me a great deal if you can identify which of the 83 changes
are new that you want to see added to the master branch and deployed.

From a process perspective, you seem to still be merging master back to
your local branch instead of creating your local topic branches off of the
current master. This makes merging your work a lot harder and introduces a
lot of uncertainty into the process. Can you help me understand what leads
up to you running "git merge ..." instead of "git checkout master; git
pull; git checkout -b NewBranch" ? The latter will create a new branch to
do the development on that will send me just the new changes in a pull
request, instead of the very convoluted history you see below in the pull
request... If we can get this process sorted, merges would take moments
instead of hours.

Thanks!

**Comment by bhjLarson** [comment]
Weren't there just two brand new files in the merge request with no
previous history?  I just created them, added them and pushed them.  There
are other changes that are not part of the merge request.  Did the somehow
git mixed?  The did not show up when I was double checking everything.

Brad

**Comment by dvhart** [comment]
I wonder if the pull request was for the wrong branch? See the link to pull
request 23. It says it was created 16 hours ago but I just noticed it says
the contributions are from 8 months ago. Maybe you accidentally sent a pull
request for the wrong branch?

**Comment by dvhart** [comment]
I've cherry-picked 7eed04f into master and added a commit to cleanup the whitespace issues and making it self-consistent. This added two files js/enrollmenterror.js and html/enrollmenterror.html. I'm assuming this was the one commit you were looking for. To avoid the confusion from the pull-request, please base development branches for pull-requests off the dvhart/bsdmaps master branch. Please don't use merge to sync with the master branch as this creates duplicate histories which we don't want in the master branch. This branch should now be deleted and all new development should be started from the current master branch.

**Pull request closed without merging**
